package com.example.wzs.myapplication.dbmanger.db_dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wzs.myapplication.dbmanger.db_dao.DrawingDataBean;
import com.example.wzs.myapplication.dbmanger.db_dao.FriendID;
import com.example.wzs.myapplication.dbmanger.db_dao.FriendMsg;
import com.example.wzs.myapplication.dbmanger.db_dao.FriendsList;
import com.example.wzs.myapplication.dbmanger.db_dao.UserInfoEntity;

import com.example.wzs.myapplication.dbmanger.db_dao.DrawingDataBeanDao;
import com.example.wzs.myapplication.dbmanger.db_dao.FriendIDDao;
import com.example.wzs.myapplication.dbmanger.db_dao.FriendMsgDao;
import com.example.wzs.myapplication.dbmanger.db_dao.FriendsListDao;
import com.example.wzs.myapplication.dbmanger.db_dao.UserInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig drawingDataBeanDaoConfig;
    private final DaoConfig friendIDDaoConfig;
    private final DaoConfig friendMsgDaoConfig;
    private final DaoConfig friendsListDaoConfig;
    private final DaoConfig userInfoEntityDaoConfig;

    private final DrawingDataBeanDao drawingDataBeanDao;
    private final FriendIDDao friendIDDao;
    private final FriendMsgDao friendMsgDao;
    private final FriendsListDao friendsListDao;
    private final UserInfoEntityDao userInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        drawingDataBeanDaoConfig = daoConfigMap.get(DrawingDataBeanDao.class).clone();
        drawingDataBeanDaoConfig.initIdentityScope(type);

        friendIDDaoConfig = daoConfigMap.get(FriendIDDao.class).clone();
        friendIDDaoConfig.initIdentityScope(type);

        friendMsgDaoConfig = daoConfigMap.get(FriendMsgDao.class).clone();
        friendMsgDaoConfig.initIdentityScope(type);

        friendsListDaoConfig = daoConfigMap.get(FriendsListDao.class).clone();
        friendsListDaoConfig.initIdentityScope(type);

        userInfoEntityDaoConfig = daoConfigMap.get(UserInfoEntityDao.class).clone();
        userInfoEntityDaoConfig.initIdentityScope(type);

        drawingDataBeanDao = new DrawingDataBeanDao(drawingDataBeanDaoConfig, this);
        friendIDDao = new FriendIDDao(friendIDDaoConfig, this);
        friendMsgDao = new FriendMsgDao(friendMsgDaoConfig, this);
        friendsListDao = new FriendsListDao(friendsListDaoConfig, this);
        userInfoEntityDao = new UserInfoEntityDao(userInfoEntityDaoConfig, this);

        registerDao(DrawingDataBean.class, drawingDataBeanDao);
        registerDao(FriendID.class, friendIDDao);
        registerDao(FriendMsg.class, friendMsgDao);
        registerDao(FriendsList.class, friendsListDao);
        registerDao(UserInfoEntity.class, userInfoEntityDao);
    }
    
    public void clear() {
        drawingDataBeanDaoConfig.clearIdentityScope();
        friendIDDaoConfig.clearIdentityScope();
        friendMsgDaoConfig.clearIdentityScope();
        friendsListDaoConfig.clearIdentityScope();
        userInfoEntityDaoConfig.clearIdentityScope();
    }

    public DrawingDataBeanDao getDrawingDataBeanDao() {
        return drawingDataBeanDao;
    }

    public FriendIDDao getFriendIDDao() {
        return friendIDDao;
    }

    public FriendMsgDao getFriendMsgDao() {
        return friendMsgDao;
    }

    public FriendsListDao getFriendsListDao() {
        return friendsListDao;
    }

    public UserInfoEntityDao getUserInfoEntityDao() {
        return userInfoEntityDao;
    }

}
